"""Converge doubled CHECK constraint names onto the canonical model names.

Revision ID: 20260811_0007
Revises: 20260801_0006
Create Date: 2026-08-11

``NAMING_CONVENTION["ck"]`` is ``ck_%(table_name)s_%(constraint_name)s``: the models pass
a *short* name (``area``) and the convention expands it to ``ck_cohort_..._area``.
Revisions 0003, 0004, and 0006 instead passed the *already expanded* name, so the
convention prefixed it a second time and the database physically stored
``ck_cohort_accounting_checks_ck_cohort_accounting_checks_area``.

That is real drift, not a comparison artifact: the migrated database and a
``create_all`` database genuinely disagree on 21 constraint names across 7 tables.
Alembic 1.19.1 began diffing CHECK constraints during autogenerate and made it visible;
1.18.5 simply never looked. The fix therefore has to change the *physical* schema, not
the comparison.

Revisions 0003, 0004, and 0006 are left exactly as they shipped. A revision must mean
the same thing forever, and rewriting them would fix only databases that have never been
built while leaving every existing one silently wrong. This revision converges the
databases that exist.

Backend differences this revision has to absorb
-----------------------------------------------

The doubled name is what SQLAlchemy *asked* for; it is not always what the backend
*stored*. Names generated by a naming convention are ``conv`` labels, which SQLAlchemy
truncates to fit ``max_identifier_length`` as ``name[: max - 8] + "_" + md5(name)[-4:]``.

* **SQLite** has no practical identifier limit, so all 21 are stored in full.
* **PostgreSQL** caps identifiers at 63 characters. 19 of the 21 exceed that and are
  stored truncated with a 4-character hash suffix; the remaining 2
  (``..._area`` at 60 and ``..._finding`` at 63) are stored whole.

So the physical name is backend-dependent and cannot be assumed. This revision asks the
live dialect what it would have produced and matches that against the constraints the
database actually reports, rather than hard-coding either backend's spelling.

Renaming is likewise backend-specific. PostgreSQL renames a constraint in place with
``ALTER TABLE ... RENAME CONSTRAINT``, which touches no row and keeps every index,
foreign key, and dependent object intact. SQLite cannot rename a CHECK constraint at all
— the name lives inside the stored ``CREATE TABLE`` text — so it needs a batch table
rebuild, which is used *only* there.

Fail-closed
-----------

Every rename is resolved to exactly one existing constraint before any DDL runs. A
missing constraint, an unexpected constraint, or two candidates for one target aborts
the revision with the names involved instead of guessing which one to rename.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, NamedTuple

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql.elements import conv

if TYPE_CHECKING:
    from sqlalchemy.engine import Connection, Dialect

revision = "20260811_0007"
down_revision = "20260801_0006"
branch_labels = None
depends_on = None


#: ``(table, canonical_name)`` for every CHECK constraint a historical revision named
#: with an already-expanded name. The canonical name is what the models declare and what
#: the database must end up with.
CANONICAL_CHECKS: tuple[tuple[str, str], ...] = (
    # 20260728_0003_market_data_evidence
    ("market_data_daily_evidence", "ck_market_data_daily_evidence_complete"),
    ("market_data_daily_evidence", "ck_market_data_daily_evidence_expected_positive"),
    ("market_data_daily_evidence", "ck_market_data_daily_evidence_volume_nonnegative"),
    (
        "market_data_evidence_constituents",
        "ck_market_data_evidence_constituents_ordinal_nonnegative",
    ),
    (
        "market_data_evidence_constituents",
        "ck_market_data_evidence_constituents_volume_nonnegative",
    ),
    # 20260730_0004_historical_replay
    ("historical_replay_sessions", "ck_historical_replay_sessions_expected_nonnegative"),
    ("historical_replay_sessions", "ck_historical_replay_sessions_status_known"),
    ("historical_replay_sessions", "ck_historical_replay_sessions_unique_nonnegative"),
    ("historical_replay_sessions", "ck_historical_replay_sessions_unique_within_expected"),
    ("historical_replay_bars", "ck_historical_replay_bars_ordinal_nonnegative"),
    ("historical_replay_bars", "ck_historical_replay_bars_volume_nonnegative"),
    ("historical_replay_observations", "ck_historical_replay_observations_correction_changes"),
    ("historical_replay_observations", "ck_historical_replay_observations_revision_one_is_first"),
    ("historical_replay_observations", "ck_historical_replay_observations_revision_positive"),
    # 20260801_0006_cohort_reviews
    ("cohort_accounting_checks", "ck_cohort_accounting_checks_area"),
    ("cohort_accounting_checks", "ck_cohort_accounting_checks_difference_has_summary"),
    ("cohort_accounting_checks", "ck_cohort_accounting_checks_finding"),
    ("cohort_accounting_checks", "ck_cohort_accounting_checks_revision_nonnegative"),
    ("cohort_operator_decisions", "ck_cohort_operator_decisions_action"),
    ("cohort_operator_decisions", "ck_cohort_operator_decisions_rationale_present"),
    ("cohort_operator_decisions", "ck_cohort_operator_decisions_revision_nonnegative"),
)


class Rename(NamedTuple):
    """One resolved rename: constraint ``old`` on ``table`` must become ``new``."""

    table: str
    old: str
    new: str
    sqltext: str


def doubled_name(table: str, canonical: str) -> str:
    """The name the convention produced when a revision passed ``canonical`` as the name.

    ``ck_%(table_name)s_%(constraint_name)s`` applied to an already-expanded name.
    """
    return f"ck_{table}_{canonical}"


def stored_name(dialect: Dialect, name: str) -> str:
    """What ``dialect`` physically stores for a convention-generated ``name``.

    ``conv`` marks the name as convention-generated, which is what makes SQLAlchemy
    truncate rather than reject it past ``max_identifier_length`` — the same code path
    that wrote the name originally, so the two agree by construction instead of by a
    reimplemented hash. ``_alembic_quote=False`` asks for the bare stored name; it is
    the documented integration point Alembic itself uses to read a constraint's name
    back without quoting.
    """
    rendered = dialect.identifier_preparer.truncate_and_render_constraint_name(
        conv(name), _alembic_quote=False
    )
    return str(rendered)


def _truncation_prefix(dialect: Dialect, name: str) -> str | None:
    """The fixed leading part a truncated form of ``name`` would keep, else ``None``."""
    limit = dialect.max_constraint_name_length or dialect.max_identifier_length
    if not limit or len(name) <= limit:
        return None
    return name[: limit - 8]


def _resolve(
    dialect: Dialect,
    table: str,
    present: dict[str, str],
    *,
    target: str,
    source: str,
    doubled: str,
) -> Rename | None:
    """Resolve one constraint to a rename, a no-op, or a fail-closed error."""
    if target in present and source in present:
        raise RuntimeError(
            f"ambiguous CHECK constraints on {table!r}: both the canonical name "
            f"{target!r} and the legacy name {source!r} exist. Resolve by hand; this "
            "revision will not guess which one the models are meant to match."
        )
    if target in present:
        return None
    if source in present:
        return Rename(table=table, old=source, new=target, sqltext=present[source])

    prefix = _truncation_prefix(dialect, doubled)
    near = sorted(n for n in present if prefix and n.startswith(prefix))
    if near:
        raise RuntimeError(
            f"ambiguous CHECK constraint on {table!r}: expected {source!r} for target "
            f"{target!r} but found only {near!r}. A truncated name that does not match "
            "the hash this dialect computes cannot be resolved safely; resolve by hand."
        )
    raise RuntimeError(
        f"missing CHECK constraint on {table!r}: neither the canonical name {target!r} "
        f"nor the legacy name {source!r} exists. Present: {sorted(present)!r}"
    )


def plan(bind: Connection, *, to_canonical: bool = True) -> list[Rename]:
    """Every rename still outstanding, resolved against the database's real constraints.

    Returns an empty list when the database already matches, which is what makes this
    revision safe to re-inspect and safe on a ``create_all`` database that never carried
    the doubled names.
    """
    inspector = sa.inspect(bind)
    dialect = bind.dialect
    tables = set(inspector.get_table_names())

    renames: list[Rename] = []
    for table, canonical in CANONICAL_CHECKS:
        if table not in tables:
            raise RuntimeError(
                f"missing table {table!r}: revisions 0003, 0004, and 0006 create every "
                "table this revision converges, so its absence means the chain did not "
                "run as declared."
            )
        present = {
            check["name"]: str(check.get("sqltext") or "")
            for check in inspector.get_check_constraints(table)
            if check.get("name")
        }
        doubled = doubled_name(table, canonical)
        legacy = stored_name(dialect, doubled)
        target, source = (canonical, legacy) if to_canonical else (legacy, canonical)
        resolved = _resolve(
            dialect, table, present, target=target, source=source, doubled=doubled
        )
        if resolved is not None:
            renames.append(resolved)
    return renames


def postgresql_rename_statement(dialect: Dialect, rename: Rename) -> str:
    """The in-place PostgreSQL rename for ``rename``, with identifiers quoted.

    Kept separate from :func:`_apply` so the emitted DDL can be asserted against the
    PostgreSQL dialect without a server, credentials, or a socket.
    """
    preparer = dialect.identifier_preparer
    return (
        f"ALTER TABLE {preparer.quote(rename.table)} "
        f"RENAME CONSTRAINT {preparer.quote(rename.old)} "
        f"TO {preparer.quote(rename.new)}"
    )


def _apply(renames: list[Rename]) -> None:
    """Rename in place on PostgreSQL; rebuild the table only where SQLite forces it."""
    if not renames:
        return

    bind = op.get_bind()
    dialect = bind.dialect

    if dialect.name == "postgresql":
        for rename in renames:
            # Native, metadata-only: no row is read or rewritten, and every index,
            # foreign key, and unique constraint on the table is untouched.
            op.execute(sa.text(postgresql_rename_statement(dialect, rename)))
        return

    if dialect.name == "sqlite":
        # SQLite stores the constraint name inside the table's CREATE TABLE text and
        # offers no way to rename it, so the table must be rebuilt. Batch mode copies
        # every row and re-declares the columns, primary key, foreign keys, unique
        # constraints, indexes, and unrelated CHECK constraints it reflected.
        by_table: dict[str, list[Rename]] = {}
        for rename in renames:
            by_table.setdefault(rename.table, []).append(rename)
        for table, table_renames in by_table.items():
            with op.batch_alter_table(table, recreate="always") as batch_op:
                for rename in table_renames:
                    # ``conv`` on *both* names is load-bearing. Alembic builds these
                    # constraints against a MetaData carrying the model's naming
                    # convention, so a bare string here would be expanded again — the
                    # exact defect this revision exists to undo, applied a third time.
                    batch_op.drop_constraint(conv(rename.old), type_="check")
                    batch_op.create_check_constraint(
                        conv(rename.new), sa.text(rename.sqltext)
                    )
        return

    raise NotImplementedError(
        f"cannot converge CHECK constraint names on dialect {dialect.name!r}; "
        "only postgresql and sqlite are supported backends"
    )


def upgrade() -> None:
    _apply(plan(op.get_bind(), to_canonical=True))


def downgrade() -> None:
    _apply(plan(op.get_bind(), to_canonical=False))
