/**
 * Deterministic offline dashboard fixtures for manual UI inspection.
 *
 * Generated by `python scripts/dashboard_fixtures.py` from real domain objects run
 * through the real operational gate and phase assessment, so what renders here is what
 * the server would send. Load one with `?fixture=<name>`, e.g. `?fixture=scheduled`.
 *
 * This module is imported dynamically behind `import.meta.env.DEV`, so it is dropped
 * from production builds rather than shipped to the served dashboard.
 */

import type { DashboardData, SleeveDetail } from "./types";

import ambiguousCohorts from "@/fixtures/ambiguous-cohorts.json";
import awaitingExecution from "@/fixtures/awaiting-execution.json";
import collecting from "@/fixtures/collecting.json";
import collectingPartial from "@/fixtures/collecting-partial.json";
import duplicateNames from "@/fixtures/duplicate-names.json";
import failed from "@/fixtures/failed.json";
import firstSessionComplete from "@/fixtures/first-session-complete.json";
import historicalCohortSelected from "@/fixtures/historical-cohort-selected.json";
import historicalCohorts from "@/fixtures/historical-cohorts.json";
import multipleCohorts from "@/fixtures/multiple-cohorts.json";
import noCohort from "@/fixtures/no-cohort.json";
import passed from "@/fixtures/passed.json";
import preClose from "@/fixtures/pre-close.json";
import reviewReady from "@/fixtures/review-ready.json";
import reviewRecorded from "@/fixtures/review-recorded.json";
import runLate from "@/fixtures/run-late.json";
import scheduled from "@/fixtures/scheduled.json";

import sleeveDetailActive from "@/fixtures/sleeve-detail-active-cohort-sleeve.json";
import sleeveDetailIncomplete from "@/fixtures/sleeve-detail-incomplete-record-sleeve.json";
import sleeveDetailLegacy from "@/fixtures/sleeve-detail-legacy-sleeve.json";
import sleeveDetailStandalone from "@/fixtures/sleeve-detail-standalone-empty-sleeve.json";
import sleeveDetailSuperseded from "@/fixtures/sleeve-detail-superseded-duplicate-name.json";

export const FIXTURES: Record<string, DashboardData> = {
  "no-cohort": noCohort as unknown as DashboardData,
  scheduled: scheduled as unknown as DashboardData,
  "pre-close": preClose as unknown as DashboardData,
  "awaiting-execution": awaitingExecution as unknown as DashboardData,
  "run-late": runLate as unknown as DashboardData,
  "first-session-complete": firstSessionComplete as unknown as DashboardData,
  collecting: collecting as unknown as DashboardData,
  "collecting-partial": collectingPartial as unknown as DashboardData,
  "review-ready": reviewReady as unknown as DashboardData,
  "review-recorded": reviewRecorded as unknown as DashboardData,
  passed: passed as unknown as DashboardData,
  failed: failed as unknown as DashboardData,
  "multiple-cohorts": multipleCohorts as unknown as DashboardData,
  "ambiguous-cohorts": ambiguousCohorts as unknown as DashboardData,
  "historical-cohorts": historicalCohorts as unknown as DashboardData,
  "historical-cohort-selected": historicalCohortSelected as unknown as DashboardData,
  "duplicate-names": duplicateNames as unknown as DashboardData,
};

export const FIXTURE_NAMES = Object.keys(FIXTURES);

/**
 * Offline fixtures for `GET /api/sleeve`, keyed by **stable sleeve id**.
 *
 * Keyed by id rather than by scenario name on purpose: that is how the drawer requests a
 * sleeve, so fixture mode exercises the same lookup the server does. Two of these share
 * the display name `trend-large` — one in the active cohort, one in the superseded cohort
 * it replaced — which is exactly the collision a name-keyed map could not represent.
 */
const SLEEVE_DETAIL_LIST: SleeveDetail[] = [
  sleeveDetailActive as unknown as SleeveDetail,
  sleeveDetailSuperseded as unknown as SleeveDetail,
  sleeveDetailLegacy as unknown as SleeveDetail,
  sleeveDetailStandalone as unknown as SleeveDetail,
  sleeveDetailIncomplete as unknown as SleeveDetail,
];

export const SLEEVE_DETAIL_FIXTURES: Record<string, SleeveDetail> = Object.fromEntries(
  SLEEVE_DETAIL_LIST.map((detail) => [detail.identity.sleeve_id, detail])
);
